### ISSUE TITLE
Writes a line to the README.md

### ISSUE THREAD

**Issue by realjvernon** [envkey/envkey-fetch#1]
When you execute the fetch it writes the following line into the README.md file:
`# envkey-fetch`

Unclear why it's writing to that file in the case of a fetch.

**Comment by danenania** [comment]
Hmm, I'm not able to reproduce this. Can you give me an example of what you're doing / how you're calling it when this happens?

**Comment by realjvernon** [comment]
Yes, we are using ENVKEY-Fetch to pull in the json configuration via
script that we use during our builds and local dev. When we install it via
the shell script it puts line in our existing readme.md.

On Jan 15, 2018 at 5:22 PM, Dane Schneider <notifications@github.com>
wrote:


Hmm, I'm not able to reproduce this. Can you give me an example of what
you're doing?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/envkey/envkey-fetch/issues/1#issuecomment-357802303>,
or mute the thread

**Comment by danenania** [comment]
I see... looking into it.

**Comment by danenania** [comment]
@klmall950 It should now be fixed. Thanks for discovering this!
