### ISSUE TITLE
Caching Strategy

### ISSUE THREAD

**Issue by skoofer** [envkey/envkey-fetch#12]
Hi @danenania , I was wondering how the caching mechanism works exactly, and whether it is a good strategy to enable it for production.

Does envkey-fetch read from the cache only when it cannot read it from the remote server? Or it reads from the cache if cache exists and doesn't even try the remote server?

Thanks in advance.

**Comment by danenania** [comment]
Hey @skoofer, it only reads from the cache when it cannot read from the remote server. 

You *could* enable it in production for a bit more reliability, but then you might end up with consistency issues, so I would suggest to leave it disabled in production in most cases. 

Ultimately it depends on your use case. The question is whether it's worse for your app to fail to start in case of network issues, or to run but with potentially outdated config. I'd say it's usually better to fail so you know there's a problem.
