### ISSUE TITLE
Tagged v1.1.0 breaks envkeygo

### ISSUE THREAD

**Issue by intabulas** [envkey/envkey-fetch#2]
As I was trying out envkey in one of my projects I noticed dep will attempt to use the tagged version of envkey-fetch when installing envkeygo. Unfortunately the 1.1.0 tag for fetch is set around jan 15 and wont work with the current envkeygo (master). Setting an override on Gopkg.toml to use envkey-fetch master solves the problem but other new users will encounter the same issue when using dep. 

The breaking issue was the change to FetchOptions on Jan 28 that added other struct members

**Comment by danenania** [comment]
Thanks for the detailed report @intabulas. To make sure I'm understanding correctly - would releasing a v1.1.1 with master fix the issue?

**Comment by intabulas** [comment]
yes it does

**Comment by danenania** [comment]
Sorry for the delay @intabulas  - there's now a v1.1.1 tag.
