### ISSUE TITLE
Size of the binaries

### ISSUE THREAD

**Issue by SeriousM** [envkey/envkey-fetch#3]
Hi!

The binary of envkey 1.1.1 for amd64 architecture is about 8.5MB in size.
I can't judge if this is necessary but wanted to ask if it's possible to reduce it.

Thanks

**Comment by danenania** [comment]
Hi @SeriousM, the binaries are large due to static linking, which allows them to be run without dependencies. Is the file size an issue for you? It could be possible to also include dynamic builds, but then you'd have to make sure your os has the right dependencies.

**Comment by SeriousM** [comment]
I've created a nuget package that carries the binary of envkey fetch. The
size of the binary defines the size of the nuget.
To serve .net users on on windows, Linux and Mac I can either carry all
three binaries or create three packages for each os which adds confusion.
I was just checking if there is a way to save some space.

Best, Bernhard Millauer

**Comment by danenania** [comment]
Yeah, the language libraries include all the binaries. It's true that it makes packages a bit large, but in practice it hasn't been a big issue for users--I think it's worth the tradeoff to work seamlessly cross-platform.

**Comment by SeriousM** [comment]
So you would prefer to publish a single package or three? I need to check
how big the package would be...

**Comment by danenania** [comment]
I'd say a single package.

**Comment by SeriousM** [comment]
I checked the size and having 3 binaries in it is about 8mb, having 1 is about 2.7mb.
This is pretty much to to pull over the wire.

I would prefer to have one package for windows (net35, net46, standard, core) and one for linux+mac as they aren't that popular for now.

What's your opinion now?

**Comment by danenania** [comment]
How about if the main package (envkey-dotnet) has all the binaries so it works everywhere by default, and then we have envkey-dotnet-windows for windows-only and a smaller file size?

**Comment by SeriousM** [comment]
I'm very familiar with the nuget economy and it's kinda hard to get the users pick the right package. They will pick the envkey package (with all binaries) because it's the most matching name.

The reason why users act like this is because there are some "upgrade-packages" for official packages by any users that just modified the code slightly to match their needs.
There is not so much help by choosing the right package and users are afraid to pick the wrong one.

I would definitely go for envkey (windows) and envkey-linux (linux, mac) as windows is the primary development plaform for .net (for now). ok?

**Comment by danenania** [comment]
Sorry, I don't mean to be stubborn about it, but I think it's important that the official lib for every language is cross-platform and 'just works' by default. In my view this is worth the extra mb. This is how the libs for every other language work and there haven't been any complaints about size.

**Comment by SeriousM** [comment]
alright, I will pack everything in a single package

**Comment by SeriousM** [comment]
Bad news on this topic, I'm not able to create a crossplatorm package because of lacking support... at least windows has a broad support for now.
