### ISSUE TITLE
Inconsistent testing of server response.

### ISSUE THREAD

**Issue by skx** [envkey/envkey-fetch#5]
[This code](https://github.com/envkey/envkey-fetch/blob/caa66ad453c613696eaa7c4ca39ec2bcfa705c0e/fetch/fetch.go#L89) looks for a HTTP-status code of ">500".

Other code in the same file, for example [this test here](https://github.com/envkey/envkey-fetch/blob/caa66ad453c613696eaa7c4ca39ec2bcfa705c0e/fetch/fetch.go#L185) looks for ">= 500". 

Testing for ">=" would seem to be the correct thing to do.  Perhaps do that every time?

**Comment by danenania** [comment]
Good catch @skx - it should be `>=` indeed
