### ISSUE TITLE
🙏 Please consider removing built binaries from this repository.

### ISSUE THREAD

**Issue by jmalloc** [envkey/envkey-fetch#6]
The `dist` directory is currently ~95MB, making git clones take an especially long time. This is especially problematic with tools like `go get` and `glide`, which provide no feedback by default and appear to be hung.

/cc @koshatul @danilvpetrov

**Comment by danenania** [comment]
Hmm, I see your point. Keeping them in the repo provides an easy source for the unzipped binaries without needing to compile, but I agree it's way too big. I'll remove `dist` and add cross-compilation instructions to the docs.

This also applies to [envkey-source](https://gitub.com/envkey/envkey-source)

**Comment by jmalloc** [comment]
Thank you for responding to this so quickly! However I've realised a problem with my suggestion, which is that the large files are still present in the Git history, and hence the clone operations are only marginally faster.

Actually speeding up the cloning would involve rewriting the commit history to exclude these files which is obviously a much bigger concern, especially if consumers are using commit hashes to pin dependencies. I understand if you do not want to do this, but perhaps this is something that could be considered as part of the next BC breaking release?

For the time being we will try using https://rtyley.github.io/bfg-repo-cleaner/ to strip these files from this history of our fork [@codeworx/envkey-fetch](https://github.com/codeworx/envkey-fetch) :)

**Comment by danenania** [comment]
Hmm, I actually did attempt to remove the dist folder from the history completely. I decided rewriting history isn't too big of a deal in this case since people can still pin to specific releases if needed. 

I used the following:

```
git filter-branch --tree-filter 'rm -rf dist' --prune-empty HEAD
git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d
git commit -m 'Removing dist from git history'
git gc
```
So clones should be sped up a lot - I wonder if the files are still hiding out somewhere.

**Comment by jmalloc** [comment]
Oh, that's great, thanks.

I'm not very familiar at all with these kind of Git operations, could it be due to the `s3_storage` branch which still has the `dist` directory?

**Comment by danenania** [comment]
Ah, that must be it.

**Comment by jmalloc** [comment]
Thanks again, we're hoping now it's just a matter of waiting for GitHub to perform a GC on the server side :)

**Comment by danenania** [comment]
I think the issue now is that in the earliest commits, there were binaries in a `bin` folder instead of `dist` and those are still hanging around. I'm working on deleting those, but haven't been successful with the filter-branch approach--I may try the repo cleaner you linked. I'll keep you posted.
