### ISSUE TITLE
Flaky responses (Important!)

### ISSUE THREAD

**Issue by SeriousM** [envkey/envkey-fetch#8]
Hi @danenania,

I was running some tests and noticed that the envkey server (?) is pretty flaky.

![image](https://user-images.githubusercontent.com/462013/48075460-9e08c200-e1e3-11e8-8fa7-7252a548c429.png)

even when I add `--timeout 10` the error occurs. This is not very deterministic and hard to explain.

**Comment by danenania** [comment]
Hi @SeriousM, sorry about that--we had a load balancer fail (and not restart automatically as it should). The immediate issue is now resolved, but there should have been a seamless failover to the S3 backup, so we're investigating why that was failing.

**Comment by SeriousM** [comment]
Is there a status page where the health status is visible?

**Comment by danenania** [comment]
Not currently, but working on getting one live today.

**Comment by SeriousM** [comment]
Awesome! Btw, how, goes the promotion of the .net library of envkey? Just
updated it to 1.2.2

**Comment by danenania** [comment]
A simple [status page](http://status.envkey.com/) is now live. Promoting dotnet lib is still on the agenda once we get v2 launched (sorry, I know it's been dragging on, but it's coming and will be worth the wait I think! )

**Comment by SeriousM** [comment]
The status page looks very nice, congratulations!
